language:
    java
jdk:
    - oraclejdk8
# TODO sudo:
    # required
# TODO services:
    # - docker
# TODO before_install:
    # - docker run -d --name neo4j -p 7687:7687 -e NEO4J_AUTH=neo4j/neo4j123 neo4j:3.1-enterprise
    # - docker ps -a
# TODO install:
    # upload to bintray
script:
    ./gradlew check jacocoTestReport assemble
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
    - bash <(curl -s https://codecov.io/bash)
# TODO after_success:
  # add integration tests
  # Add uploading
# TODO after_script:
    # - docker rm -f neo4j
